class ErrorCodes:

    # HTTP Status Codes
    HTTP_SUCCESS = 200
    HTTP_CREATED = 201
    HTTP_BAD_REQUEST = 400

    ERROR_SUCCESS = 200
    ERROR_SCHEMA_VALIDATION = 201
    ERROR_UNKNOWN = 202

    # Custom Errors
    SUBJECT_NOT_FOUND = 400
    POST_NOT_FOUND = 401
