class ErrorCodes:

    # HTTP Status Codes
    HTTP_STATUS_SUCCESS = 200
    HTTP_STATUS_CREATED = 201
    HTTP_STATUS_BAD_REQUEST = 400
    HTTP_STATUS_NOT_FOUND = 404

    SUCCESS = 200
    SCHEMA_VALIDATION = 201
    UNKNOWN = 202

    # Custom Errors
    SUBJECT_NOT_FOUND = 400
    POST_NOT_FOUND = 401
