"""added created_date to practice

Revision ID: 1d61ae9f043d
Revises: 18d3f41b79c0
Create Date: 2019-03-10 12:40:28.001394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d61ae9f043d'
down_revision = '18d3f41b79c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practices', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_practices_created_date'), 'practices', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practices_created_date'), table_name='practices')
    op.drop_column('practices', 'created_date')
    # ### end Alembic commands ###
