"""rename table and models from nodes to subjects

Revision ID: df52accfdcd7
Revises: d22c9cbef954
Create Date: 2019-03-10 10:27:11.875374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df52accfdcd7'
down_revision = 'd22c9cbef954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('nodes', 'subjects')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('subjects', 'nodes')
    # ### end Alembic commands ###
