"""alter data type for teaching point to text

Revision ID: 99d4ffab73f4
Revises: 6066db7fbfbf
Create Date: 2019-06-21 12:46:23.722437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d4ffab73f4'
down_revision = '6066db7fbfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practices', 'teaching_point',
                    existing_type=sa.String(length=250), type_=sa.Text())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practices', 'teaching_point',
                    existing_type=sa.Text(), type_=sa.String(length=250))
    # ### end Alembic commands ###
